### ISSUE TITLE
Обзор способов хранения данных: XML/JSON/DB/...

### ISSUE THREAD

**Issue by Tvord** [Entering-IT/documentation#13]
Краткий экскурс по всему: файлики через /n, XML, JSON, БД (возможно что-то ещё)
Плюсы и минусы каждого, когда стоит использовать
Если останется время - разница БД - SQLite/постгря/мускуль/... (хотя это скорее отдельная тема)

**Comment by Silverchiffa** [comment]
Грозился Семен, кажется?

**Comment by Tvord** [comment]
Зачитано
