### ISSUE TITLE
Основы Linux

### ISSUE THREAD

**Issue by Tvord** [Entering-IT/documentation#3]
1. Что это и с чем его едят
2. Дистрибутивы. Различия, назначение
3. Пакетные менеджеры, поиск нужного софта
4. Настройки сети
------------------
Это далеко не всё, но хватит для того чтобы спокойно начать работать с ним

**Comment by Softovick** [comment]
Так как на субботний доклад дается всего 20 минут вместе с вопросами, то рассмотрение вышеописанных вопросов либо будет вскольз, либо строить доклад в стиле "тед лайк", как писали в чате.
Соответственно, второй варианты тем:
- Боятся или не боятся Linux.
- Что это такое вообще, почему его важно изучить, почему вообще о нем стали так много говорить.
- Дистрибутивы, сборки, как выглядит один или два из популярных дистрибутивов (виртуальная машина с GUI и без).
- Почему новичкам в РФ особенно важно изучать Linux и какой.
- Вопросы, как искать ответы, к чему готовится.

**Comment by Silverchiffa** [comment]
Успешно зачитан :)
