### ISSUE TITLE
Основы сетевого взаимодействия

### ISSUE THREAD

**Issue by jinxman1** [Entering-IT/documentation#35]
Кратко о том, как выглядит сетевое взаимодействие устройств - сетевая модель OSI, TCP/IP, DNS и тд. Ввиду небольшого опыта в программировании, не смогу сделать акцент на соответствующей части, но постараюсь дать некую общую картину того, как это работает, без углубления в детали, более подходящие для сисадминов/девопсов.
Поскольку речь будет идти о самых основах, выступление будет интересно скорее начинающим свой путь в ИТ, нежели опытным программистам.
Предварительная дата: 27.11, Максим.

**Comment by Silverchiffa** [comment]
Доклад прочитан :)
