### ISSUE TITLE
Основы Docker

### ISSUE THREAD

**Issue by Tvord** [Entering-IT/documentation#4]
1. Что это и с чем его едят
2. Image и Container
3. Как поднять готовый контейнер и настроить его

**Comment by Softovick** [comment]
Доклад короткий:
- Докер, почему его используют, почему он такой популярный.
- Основные понятие в Docker
- Варианты работы с Docker (Docker Desktop, Docker Linux, Docker-Compose, Docker Swarm). Вскольз о Kubernetes.
- Пример создания и работы с кодом при исопльзовании Docker.

**Comment by Silverchiffa** [comment]
Доклад прочитан
