### ISSUE TITLE
Основы SQL

### ISSUE THREAD

**Issue by jensaymoo** [Entering-IT/documentation#8]
Что такое SQL? Да чего он нужен и как его использовать.

**Comment by Silverchiffa** [comment]
Successfully done

**Comment by starovoytovprog** [comment]
Примеры написаны для T-SQL. Для других диалектов возможно понадобятся корректировки.

### Операторы, которые управляют структурой БД.
Команда CREATE используется для создания объектов. Если мы хотим создать таблицу, то пишем _CREATE TABLE_ и описываем таблицу, которую хотим создать. Давайте создадим таблицу:

_create table table1 (
	id int,
	insertDate date,
	context varchar(max)
)_

В этой таблице мы объявили три поля - идентификатор, дата вставки и какой-то контекст. Я каждое поле разместил на отдельной строке, чтобы было более понятно, что к чему относится. Как видим, описание столбца состоит из двух значений - его имя, и его тип.

Добавим сразу команду удаления таблицы:

_drop table table1_

Делаю это сразу, чтобы мы могли много раз пересоздавать нашу таблицу и СУБД не ругалась на то, что этот объект уже создан.
Первое поле у нас - идентификатор, и очень хотелось бы, чтобы это поле не было _null_, было уникальным и нам самим не нужно было выдумывать значения для каждой вставки данных. Для этих целей в ms sql есть ключевое слово _identity_, которое принимает начальное значение и шаг. Добавим это описание:

_create table table1 (
	id int identity(1, 1),
	insertDate date,
	context varchar(max)
)_

Поле _insertDate_ судя по своему названию должно содержать дату вставки, её тоже не хотелось бы вносить каждый раз самостоятельно. Для этого есть ключевое слово _default_. Текущую дату можно получить вызвав функцию _getdate()_. Напомню, что для других СУБД эти моменты могут отличаться, но это не имеет принципиального значения. Объявление таблицы примет следующий вид:

_create table table1 (
	id int identity(1, 1),
	insertDate date default getdate(),
	context varchar(max)
)_

Кроме того, хотелось бы, чтобы дата и время вставки были всегда, поэтому добавим ограничение _not null_ и создание первой таблицы у нас примет следующий вид.

_create table table1 (
	id int identity(1, 1),
	insertDate date not null default getdate(),
	context varchar(max)
)_

Для поля _context_ мы никакого ограничения не хотим, пусть это будет произвольная строка. Ну или не будет, если это будет _null_. Давайте создадим ещё одну таблицу (сразу с командой удаления), пусть она будет такого вида:

_create table table2 (
	id int identity(1, 1),
	table1_id int not null,
	[key] varchar(max) not null,
	value varchar(max)
)_

_drop table table2_

Обратите внимание на имя поля _[key]_, которое я заключил в квадратные скобки. _key_ является ключевым словом, но таким образом я его экранировал для использования в качестве имени столбца. Никогда так не делайте, давайте столбцам и таблицам приличные имена.
В каждой таблице у нас есть поле _id_. Оно является ненатуральным ключом, объявим их как первичные ключи в этих таблицах. Чтобы добавить ключ, таблицу нужно обновить, поэтому понадобится команда _alter_.

_alter table table1
add constraint pk_table1 primary key (id)_

_alter table table2
add constraint pk_table2 primary key (id)_

Вторая таблица имеет собственный идентификатор, а так же идентификатор записи первой таблицы, т.е. она на неё ссылается. Далее в ней указано непустое поле _key_ и произвольное _value_. С помощью этой таблицы мы можем добавить произвольное количество свойств для каждой записи первой таблицы. Но раз уж вторая таблица хочет ссылаться на первую, давайте зафиксируем это средствами SQL и добавим во вторую таблицу ссылку на первую. Так же с помощью команды _alter_.

_alter table table2 add constraint fk_case_casePack foreign key (table1_id)
references table1 (id)_

И последний штрих, сделаем так, чтобы во второй таблице для первой можно было добавить только один ключ. Для этого мы сделаем уникальной пару _table1_id, [key]_.

_alter table table2 add constraint unic_table1_key unique(table1_id, [key])_

Итак, у нас получилась схема из двух связанных между собой таблиц. Ранее я упоминал команду _truncate_ - усечение, давайте рассмотрим, что же делает она. _truncate_ удаляет все записи из таблицы, а так же сбрасывает счётчик _identity_, при этом не добавляя записи в журнал. За счёт этого очистка таблицы происходит намного быстрее, но при этом есть ряд ограничений. Например, в нашей схеме мы не можем сделать так:

_truncate table table1_

Потому что _table2_ ссылается на _table1_. Более того, на команду _truncate_ требуется разрешение не на удаление контента, а на изменение структуры БД, что само по себе намекает на то, что всё не так просто. Будьте предельно аккуратны, используя эту команду.

### Операторы для работы с данными.
Первый - это оператор _insert_. Он добавляет данные в таблицу. Давайте добавим данные в первую таблицу.

_insert into table1 (context) values ('context 1')_

После имени таблицы указывается список столбцов, после - список значений. Мы создавали таблицу таким образом, чтобы _id_ и _insertDate_ заполнялись самостоятельно, поэтому нам нужно указать лишь _context_. Давайте теперь посмотрим на данные, которые мы вставили. Для этого воспользуемся оператором select.

_select *
from table1_

Здесь команда _select_ состоит из двух предложений - что мы выбираем, и откуда. Звёздочка означает, что мы выбираем все столбцы. Давайте добавим ещё пару записей.

_insert into table1 (context) values ('context 2')
insert into table1 (context) values ('context 3')_

Теперь у нас выбираются три записи. Добавим ключевое слово _where_.

_where id = 1_

Ключевое слово _where_ нужно для ограничения записей, которые мы выбираем. В данном случае мы выбираем только первую запись. Но с одной табличкой скучно, давайте заполним вторую.

_insert into table2 (table1_id, [key], value) values (1, 'order', 2)
insert into table2 (table1_id, [key], value) values (2, 'order', 1)
insert into table2 (table1_id, [key], value) values (3, 'order', 3)
insert into table2 (table1_id, [key], value) values (1, 'pow', 700)
insert into table2 (table1_id, [key], value) values (2, 'pow', 200)
insert into table2 (table1_id, [key], value) values (3, 'pow', -100)_

Теперь в запрос на выборку добавим вторую таблицу. Используем для этого ключевое слово _join_. Обратим внимание, что теперь в предложении _where_ необходимо указывать таблицу, к которой этот столбец относится, так как появилась неоднозначность.

_select *
from table1
join table2 on table1.id = table2.table1_id
where table1.id = 1_

Мы видим проперти, которые относятся к первому контексту. Допустим мы хотим отфильтровать контексты, мощность которых больше 0. Для этого к выражению _on_ добавим условие, по которому мы выбираем не все ключи, а только _pow_ и фильтр по этому ключу. Убираем ключевое слово _where_, чтобы выбрать все контексты.

_select *
from table1
join table2 on table1.id = table2.table1_id and table2.[key] = 'pow' and table2.value > 0_

Теперь мы отсортируем записи по ключу _order_, для этого присоединим таблицу _table2_ ещё раз. И здесь уже не обойтись без алиасов - именований таблиц в рамках запроса. И добавим ключевое слово _order_ для сортировки.

_select *
from table1 t1
join table2 keyPow on t1.id = keyPow.table1_id and keyPow.[key] = 'pow' and keyPow.value > 0
join table2 keyOrder on t1.id = keyOrder.table1_id and keyOrder.[key] = 'order'
order by keyOrder.value_

Здесь можно ограничить вывод столбцов, допустим нам нужен только контекст и его мощность.

_select t1.context as [Контекст], keyPow.value as [Мощность]
from table1 t1
join table2 keyPow on t1.id = keyPow.table1_id and keyPow.[key] = 'pow' and keyPow.value > 0
join table2 keyOrder on t1.id = keyOrder.table1_id and keyOrder.[key] = 'order'
order by keyOrder.value_

Итак, у нас есть простая, маленькая выборка. Давайте немного остановимся на ключевом слове _join_, какие бывают соединения. Есть следующие типы соединений:

_inner_ - внутреннее соединение, используется по умолчанию. При его использовании выводятся те строки, для которых условие в _on_ выполняется.
_left/right_ левые и правые соединения отличаются от внутреннего тем, что одна из таблиц попадёт в выборку в любом случае. Давайте для эксперимента добавим записи, чтобы это продемонстрировать.

_insert into table1 (context) values ('context 4')_

_select t1.context as [Контекст], keyPow.value as [Мощность]
from table1 t1
left join table2 keyPow on t1.id = keyPow.table1_id and keyPow.[key] = 'pow' and keyPow.value > 0
left join table2 keyOrder on t1.id = keyOrder.table1_id and keyOrder.[key] = 'order'
order by keyOrder.value_

Мы видим, что в выборку попали все контексты, даже те, для которых условия в on не выполнялись. _right_ - то же самое, только наоборот.

_full join_ выводит все записи из всех таблиц, соединив те, для которых выполнилось условие _on_. Как видите, ничего сложного в этом нет, особенно если в запросе не участвует большое количество таблиц. Для объединения можно вообще не использовать _join_, а просто указать все таблицы в _from_ и прописать все условия в _where_.

_select t1.context as [Контекст], keyPow.value as [Мощность]
from table1 t1, table2 keyPow, table2 keyOrder
where t1.id = keyPow.table1_id and keyPow.[key] = 'pow' and keyPow.value > 0 and t1.id = keyOrder.table1_id and keyOrder.[key] = 'order'
order by keyOrder.value_

Результат выборки будет тем же, но посмотрите в какую кашу превратился запрос, а он довольно маленький. Можете представить, что будет с большим запросом на несколько экранов. SQL-запросы это тоже код, читаемость и поддерживаемость для него не менее важна, чем для всего остального вашего проекта.

_select t1.context as [Контекст], keyPow.value as [Мощность]
from table1 t1
left join table2 keyPow on t1.id = keyPow.table1_id and keyPow.[key] = 'pow' and keyPow.value > 0
left join table2 keyOrder on t1.id = keyOrder.table1_id and keyOrder.[key] = 'order'
order by keyOrder.value_

### Транзакции и обработка ошибок.
Теперь давайте перейдём к третьей группе операторов - это транзакции и обработка ошибок. Поэтому давайте посмотрим, как в MS SQL можно с этим работать. Допустим мы хотим вставить две строки во вторую таблицу.

_insert into table2 (table1_id, [key], value) values (3, 'top', 10)
insert into table2 (table1_id, [key], value) values (3, 'pow', 10)_

_select * from table2_

Одна строка не вставилась, поэтому вывелось семь. Но что если мы хотим или вставить всё или вообще ничего. Давайте откроем транзакцию.

_begin transaction_

_insert into table2 (table1_id, [key], value) values (3, 'top', 10)
insert into table2 (table1_id, [key], value) values (3, 'pow', 10)_

_commit_

Всё равно семь строк. В этой ситуации нужно обработать ошибку. И делается это с помощью всем известной конструкции - _try-catch_. Только записывается это немного своеобразно. Открываем блок _try_, в нём открываем транзакцию и делаем _commit_, а в блоке _catch_ сделаем _rollback_.

_begin try_
	begin transaction	
	insert into table2 (table1_id, [key], value) values (3, 'top', 10)
	insert into table2 (table1_id, [key], value) values (3, 'pow', 10)
	commit
end try
begin catch
	rollback
end catch_

При этом, если мы будем вставлять данные без ошибок - то вставятся они все и выведется 8 строк.

_begin try
	begin transaction
	insert into table2 (table1_id, [key], value) values (3, 'top', 10)
	insert into table2 (table1_id, [key], value) values (3, 'bottom', 10)
	commit
end try
begin catch
	rollback
end catch_

Хочу обратить внимание, что это - плохая запись. Здесь мы подавили ошибку и больше её не видим. Но информация о ней всё ещё доступна в блоке _catch_, не надо её забывать. Давайте её просто выведем.

_begin try
	begin transaction
	insert into table2 (table1_id, [key], value) values (3, 'top', 10)
	insert into table2 (table1_id, [key], value) values (3, 'pow', 10)
	commit
end try
begin catch
	print ERROR_MESSAGE()
	rollback
end catch_

Итак, подведём небольшой итог. Сегодня мы рассмотрели как с помощью SQL создавать связные таблицы, как в них создавать связи и ограничения, как осуществлять вставку в транзакции и как можно обработать ошибку в ней, а так же сделали небольшую выборку с присоединением таблиц.
